apiVersion: apps/v1
kind: Deployment
metadata:
  name: openefsafoodex2scafrontend
spec:
  selector:
    matchLabels:
      app: openefsafoodex2scafrontend
  template:
    metadata:
      labels:
        app: openefsafoodex2scafrontend
    spec:
      containers:
      - name: openefsafoodex2scafrontend
        image: foodex2sca:frontend
        # image: efsadsreg.azurecr.io/openefsafoodex2scafrontend
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: openefsafoodex2scafrontendservice
spec:
  selector:
    app: openefsafoodex2scafrontend
  ports:
  - port: 8081
  type: LoadBalancer