apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodex2scafrontend
spec:
  selector:
    matchLabels:
      app: foodex2scafrontend
  template:
    metadata:
      labels:
        app: foodex2scafrontend
    spec:
      containers:
      - name: foodex2scafrontend
        image: foodex2sca:frontend
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: foodex2scafrontendservice
spec:
  selector:
    app: foodex2scafrontend
  ports:
  - port: 80
    targetPort: 8081
  type: LoadBalancer
